### ISSUE TITLE
1.13 compatibility?

### ISSUE THREAD

**Issue by NatoBoram** [MLG-Fortress/PopulationDensity#45]
Hello! I just fired up a new Spigot 1.13 development build and I noticed there was an error. Also, it's not clear what's the latest version and where to download it. On [SpigotMC](https://www.spigotmc.org/resources/%E2%98%85-%E2%98%86-populationdensity-%E2%98%86-%E2%98%85.7995/), it says 5.4.1, on [Aquifer](https://aquifermc.org/resources/populationdensity.19/) it says 5.9, and on [GitHub](https://github.com/TechFortress/PopulationDensity/releases) it says 5.10, but in-game it says 5.1 so it's confusing.

**5.4**

```
[22:52:23 INFO]: PopDensity: Examining available resources in region "0 0"...
[22:52:23 WARN]: [PopulationDensity] Task #2 for PopulationDensity v5.4.1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.ChunkSnapshot.getBlockTypeId(III)I
        at me.ryanhamshire.PopulationDensity.PopulationDensity.scanRegion(PopulationDensity.java:1140) ~[?:?]
        at me.ryanhamshire.PopulationDensity.ScanOpenRegionTask.run(ScanOpenRegionTask.java:9) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**5.10**

```
[22:59:37 INFO]: [PopulationDensity] Examining available resources in region "0 0"...
[22:59:37 WARN]: [PopulationDensity] Task #2 for PopulationDensity v5.1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.ChunkSnapshot.getBlockTypeId(III)I
        at me.ryanhamshire.PopulationDensity.PopulationDensity.scanRegion(PopulationDensity.java:1289) ~[?:?]
        at me.ryanhamshire.PopulationDensity.ScanOpenRegionTask.run(ScanOpenRegionTask.java:9) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

It looks like the function `org.bukkit.ChunkSnapshot.getBlockTypeId` got removed in latest Spigot build, and a lot of stuff was renamed.

**First Join**

```
[23:05:32 INFO]: [PopulationDensity] Assigned new player NatoBoram to region redstone at 0 0.
[23:05:33 INFO]: NatoBoram[/127.0.0.1:57414] logged in with entity id 169 at ([world]-14.5, 70.0, -18.5)
>op NatoBoram
[23:05:34 ERROR]: Could not pass event ChunkLoadEvent to PopulationDensity v5.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.ChunkMap.a(ChunkMap.java:41) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.ChunkMap.put(ChunkMap.java:134) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.ChunkMap.put(ChunkMap.java:1) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.Long2ObjectMaps$SynchronizedMap.put(Long2ObjectMaps.java:371) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.a(ChunkProviderServer.java:207) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source) [?:?]
        at java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source) [?:?]
        at java.util.concurrent.CompletableFuture.thenApply(Unknown Source) [?:?]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.generateChunk(ChunkProviderServer.java:169) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:127) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.loadChunk(CraftWorld.java:269) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.loadChunk(CraftWorld.java:161) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.getHighestBlockYAt(CraftWorld.java:103) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.getHighestBlockAt(CraftWorld.java:577) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.getHighestBlockAt(CraftWorld.java:581) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at me.ryanhamshire.PopulationDensity.PopulationDensity.getRegionCenter(PopulationDensity.java:1357) [PopulationDensity.jar:?]
        at me.ryanhamshire.PopulationDensity.PopulationDensity.TeleportPlayerToRegion(PopulationDensity.java:1225) [PopulationDensity.jar:?]
        at me.ryanhamshire.PopulationDensity.PlaceNewPlayerTask.run(PlaceNewPlayerTask.java:41) [PopulationDensity.jar:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
        at me.ryanhamshire.PopulationDensity.DataStore.AddRegionPost(DataStore.java:596) ~[?:?]
        at me.ryanhamshire.PopulationDensity.WorldEventHandler.onChunkLoad(WorldEventHandler.java:91) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        ... 28 more
[23:05:36 WARN]: [PopulationDensity] Task #18 for PopulationDensity v5.1 generated an exception
java.lang.NoSuchFieldError: ENTITY_ENDERMEN_TELEPORT
        at me.ryanhamshire.PopulationDensity.TeleportPlayerTask.run(TeleportPlayerTask.java:123) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

I hope you have the intention of bringing it to 1.13 :)

**Comment by RoboMWM** [comment]
idk why in-game it's 5.1, but bukkitdev contains the latest version. SpigotMC's version isn't managed by me, and Aquifer was down for a week a few weeks ago so I wasn't able to update anything there.

There's quite a bit of deprecated code in here, but one of the ones that was used (and afaik, there still is no replacement(?) is `Block#setTypeAndId` iirc, which is used to set the signs (both the sign and its position). I haven't dealt too much with setting states in the world, so I'm unsure if it's possible to accomplish the same via blockstates… since afaik these need to be already-existing in the world. (Doesn't work in our case since we need to set the data before placing it, else it'll just pop off immediately since it's placed in the wrong direction, from what I recall.)

I know there's #30 which needs to be updated (if it will be), I also don't know if @Developaws is working on anything. Unsure if I'll get to it this week, dealing with paperwork to prevent paying for something unnecessary and other life events :s but PRs are welcome!

**Comment by ghost** [comment]
I'll put out a "temporary" patch later today =]
