### ISSUE TITLE
Error on spigot 1.13 when checking chunks for resources

### ISSUE THREAD

**Issue by THENATHE** [MLG-Fortress/PopulationDensity#51]
```
[02:14:38] [Server thread/INFO]: [PopulationDensity] Examining available resources in region "0 1"...
[02:14:38] [Server thread/WARN]: [PopulationDensity] Task #2 for PopulationDensity v5.1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.ChunkSnapshot.getBlockTypeId(III)I
	at me.ryanhamshire.PopulationDensity.PopulationDensity.scanRegion(PopulationDensity.java:1289) ~[?:?]
	at me.ryanhamshire.PopulationDensity.ScanOpenRegionTask.run(ScanOpenRegionTask.java:9) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot.jar:git-Spigot-69774b3-272426a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

**Comment by THENATHE** [comment]
Solved in the prerelease that I found through looking through some comments
