### ISSUE TITLE
Error when renaming regions

### ISSUE THREAD

**Issue by THENATHE** [MLG-Fortress/PopulationDensity#53]
Despite the error, the region is still renamed on server restart

```
[02:19:54] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'renameregion' in plugin PopulationDensity v5.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-69774b3-272426a]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot.jar:git-Spigot-69774b3-272426a]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot.jar:git-Spigot-69774b3-272426a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
	at me.ryanhamshire.PopulationDensity.DataStore.AddRegionPost(DataStore.java:596) ~[?:?]
	at me.ryanhamshire.PopulationDensity.PopulationDensity.nameRegion(PopulationDensity.java:1056) ~[?:?]
	at me.ryanhamshire.PopulationDensity.PopulationDensity.onCommand(PopulationDensity.java:728) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-69774b3-272426a]
	... 15 more
```

**Comment by THENATHE** [comment]
Solved in the prerelease that I found through looking through some comments
