### ISSUE TITLE
1.14.1 Paper 26 ChunkUnloadEvent Spam

### ISSUE THREAD

**Issue by ichbinashh** [MLG-Fortress/PopulationDensity#70]
https://pastebin.com/6GUiTeuv

Spams periodically, but seems to happen every time upon leaving the server. (At least from what I can gather on my test server, my public is yet to update to 1.14)

**Comment by RoboMWM** [comment]
```
[15:57:43 ERROR]: Could not pass event ChunkUnloadEvent to PopulationDensity v5.11.2
java.lang.NoSuchMethodError: org.bukkit.event.world.ChunkUnloadEvent.setCancelled(Z)V
        at me.ryanhamshire.PopulationDensity.WorldEventHandler.onChunkUnload(WorldEventHandler.java:194) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor272.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.1.jar:git-Paper-26]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.1.jar:git-Paper-26]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.1.jar:git-Paper-26]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$a$9(PlayerChunkMap.java:356) ~[patched_1.14.1.jar:git-Paper-26]
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:499) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:195) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1004) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:988) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:971) ~[patched_1.14.1.jar:git-Paper-26]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:906) ~[patched_1.14.1.jar:git-Paper-26]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

**Comment by RoboMWM** [comment]
if this event no longer implements Cancellable, I wonder if there is an easy way to keep a chunk loaded.

**Comment by ichbinashh** [comment]
_After updating to the most recent version of Paper, this seems to have been resolved. I'll let you know if I see it happen again_

Forget that, it seems to be doing it again for some reason.

https://pastebin.com/1xfR6xjJ

It seems to do it any time I leave the spawn chunk and reenter it. Previously it was doing it on logout.

**Comment by ichbinashh** [comment]
Just to let you know, this is still happening in Paper(51) 1.14.2-R0.1-SNAPSHOT

https://pastebin.com/eGqJRm8j

**Comment by RoboMWM** [comment]
Yea, seems it's no longer cancelable. I'll see if spigot has implemented the "force-load" API - otherwise, keeping region post chunks loaded will be removed or become a paper-only feature.

**Comment by smellyonionman** [comment]
Paper-only please!!!  I run a few plugins like that already, one entirely so.

**Comment by ichbinashh** [comment]
Hey, I was just wondering if you were any closer to providing a solution to this?

**Comment by wizjany** [comment]
@RoboMWM check `World#loadChunk` vs `World#getChunkAt` javadocs.

**Comment by RoboMWM** [comment]
Thanks @wizjany. It seems I can also do chunk#setForceLoaded. But unsure if it might be too late on chunk unload event, and may have to just call world#loadChunk anyways.
